# Generated by Django 4.0.3 on 2022-04-10 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
