# Generated by Django 4.0.3 on 2022-04-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Participants',
            new_name='participants',
        ),
    ]
